language: android
jdk: oraclejdk7
sudo: false

branches:
   only:
      - unstable

android:
   components:
      - build-tools-21.1.1
      - android-21
env:
   global:
      # install timeout in minutes
      - ADB_INSTALL_TIMEOUT=8

# Create and start the emulator
before_script:
   - echo no | android create avd --force -n test -t android-21  --abi armeabi-v7a -c 128M
   - emulator -avd test -no-skin -no-audio -no-window &
   - android-wait-for-emulator
   - adb shell inout keyevent 82 &

script:
   - ./gradlew assembleDebug
   - ./gradlew build connectedCheck --debug
